NO_LAW_FOUND = "No sufficiently relevant and authoritative legal provision was found for this query."
INSUFFICIENT_SOURCE = "Relevant law exists, but authoritative source is missing."
OUTDATED_DATA = "Law found, but amendment status is uncertain."
NON_LEGAL_QUERY = "This query does not appear to be related to Indian law."
UNDERSPECIFIED_QUERY = "Please provide more specific legal details or keywords (e.g., 'section', 'act', 'crime')."
